version: "3"
services:
  postgres:
    container_name: "postgres-${PROJECT_PATH}"
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-node:
    container_name: "node-${PROJECT_PATH}"
    image: onfinality/subql-node:v5.6.0
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_POST: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/${PROJECT_PATH}
      - --disable-historical=true
      - --batch-size=1

  graphql-engine:
    container_name: "query-${PROJECT_PATH}"
    image: onfinality/subql-query:v1.5.0
    ports:
      - 3000:3000
    depends_on:
      - subquery-node
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
