specVersion: 0.0.1
description: Fearless SubQuery project
repository: ''
schema: ./schema.graphql
network:
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 5439260 # block a bit before one with batch with reward_stakers
    mapping:
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
