specVersion: 0.0.1
description: Fearless SubQuery project
repository: 'https://github.com/ef1rspb/subquery-fearless'
schema: ./schema.graphql
network:
  endpoint: 'wss://kusama-rpc.polkadot.io'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    # for polkadot startBlock: 5350000
    mapping:
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
