specVersion: 0.2.0
name: nova
version: 1.0.0
description: Nova SubQuery project
repository: https://github.com/nova-wallet/subquery-nova
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x262e1b2ad728475fd6fe88e62d34c200abe6fd693931ddad144059b1eb884e5b'
  endpoint: wss://hk.p.bifrost-rpc.liebi.com/ws
  dictionary: https://api.subquery.network/sq/subquery/bifrost-parachain-dictionary
  chaintypes:
    file: './BifrostTypes.json'

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 20130
    mapping:
      file: ./dist/src/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleAssetTransfer
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred
        - handler: handleCurrencyTransfer
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: handleTokenTransfer
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer
        - handler: handleParachainRewarded
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Rewarded