specVersion: 0.2.0
name: nova
version: 1.0.0
description: Nova SubQuery project
repository: https://github.com/nova-wallet/subquery-nova
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  endpoint: wss://wss.api.moonbeam.network
  dictionary: https://api.subquery.network/sq/subquery/moonbeam-dictionary
  chaintypes:
    file: './dist/chaintypes.js'

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/src/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed
        - handler: handleBonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleUnbonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Unbonded
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
        - handler: handleNewEra
          kind: substrate/EventHandler
          filter:
            module: staking
            method: StakingElection
        - handler: handleStakersElected
          kind: substrate/EventHandler
          filter:
            module: staking
            method: StakersElected