name: PR check
on:
  pull_request:

jobs:
  pr:
    name: build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: yarn install
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
